name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      git_commit:
        description: "Git Commit Hash or Branch Name"
        required: true
        default: 'master'  

env:
  DOCKER_REPO: inventoryclient12311111.azurecr.io

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Inventory Server Build
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:

      # - uses: act10ns/slack@v1
      #   with:
      #     status: starting
      #   if: always()

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.git_commit}}
          fetch-depth: 0

      - name: Configure GitVersion
        shell: bash
        run: |
          echo "mode: Mainline" > GitVersion.yml
          echo "branches: {}" >> GitVersion.yml
          echo "ignore:" >> GitVersion.yml
          echo "  sha: []" >> GitVersion.yml

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        # with:
        #   additionalArguments: '/showConfig'
      
      - name: Extract branch name and clean up special characters
        shell: bash
        run: |
          uncleanBranchName=$(echo ${GITHUB_REF#refs/heads/})
          cleanedBranchName=$(echo $uncleanBranchName | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
          echo "Unclean: $uncleanBranchName - Clean: $cleanedBranchName"
          echo "##[set-output name=branch;]$(echo $cleanedBranchName)"
          echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
        id: extract_branch

      - name: Build Docker Images
        id: Build_Docker_Images
        run: |
          export IMAGE_TAG=$GITVERSION_SHORTSHA
          docker-compose build \
            --build-arg COMMIT_HASH=$GITVERSION_SHA \
            --build-arg IMAGE_VERSION=$GITVERSION_FULLSEMVER \
            --build-arg IMAGE_VERSION_LONG=$GITVERSION_INFORMATIONALVERSION \

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REPO }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Publish Images
        id: Push_Docker_Images
        run: |
          echo BRANCH: $GITVERSION_ESCAPEDBRANCHNAME
          echo VERSION: $GITVERSION_FULLSEMVER

          BRANCH_NAME=$GITVERSION_ESCAPEDBRANCHNAME
          IMAGE_VERSION=$GITVERSION_FULLSEMVER

          for image in `docker images ${{ env.DOCKER_REPO }}/*:${GITVERSION_SHORTSHA} --format "{{.Repository}}"`
          do

            docker tag ${image}:$GITVERSION_SHORTSHA ${image}:$IMAGE_VERSION
            docker tag ${image}:$GITVERSION_SHORTSHA ${image}:$BRANCH_NAME

            docker push ${image}:$GITVERSION_SHORTSHA
            docker push ${image}:$IMAGE_VERSION
            docker push ${image}:$BRANCH_NAME

            #docker rmi ${image}:$GITVERSION_SHORTSHA
            #docker rmi ${image}:$IMAGE_TAG

          done

      # - name: Trigger deployment
      #   id: trigger_deployment
      #   if: contains(github.ref, 'develop')
      #   run: |
      #     curl -X POST https://api.github.com/repos/LakesideLabs/inventory.bootstrap/dispatches \
      #     -H 'Authorization: Bearer ${{ secrets.ACTIONS_ACCESS_TOKEN }}' \
      #     --data '{"event_type": "docker_build_complete","client_payload": {"apiimagetag": "develop", "uiimagetag": "develop", "environment": "dev", "host": "aexinventorydev.eastus.cloudapp.azure.com"}}'

      # - uses: act10ns/slack@v1
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #   if: always()