name: Destory Virtual Machine

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the Virutal Machine"
        required: true          

jobs:

  destroy:
    runs-on: ubuntu-latest
    name: Destory Virtual Machine
 
    steps:

      - name: Cleanup Docker Stack
        id: Docker
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: "aexautodeploy${{github.event.inputs.name}}.eastus.cloudapp.azure.com"
          key: ${{ secrets.AEX_SSH_PRIVATE_KEY }}          
          user: 'azureuser'
          last_ssh: |
            export NODE_ID=$(docker info -f '{{.Swarm.NodeID}}')
            export DOCKER_SWARM_HOST=$(docker info --format "{{ (index .Swarm.RemoteManagers 0).Addr }}")
            export DOCKER_SWARM_HOST=${DOCKER_SWARM_HOST/2377/2374}
            docker -H $DOCKER_SWARM_HOST stack rm inventory_${{github.event.inputs.name}} || true
            (docker swarm leave && sleep 30) || true            
            docker -H $DOCKER_SWARM_HOST node rm $NODE_ID || true            

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Destroy VM
        id: Destroy_VM
        uses: azure/CLI@v1
        with:
          inlineScript: |
            VM_NAME="auto-vm-${{github.event.inputs.name}}"
            PRINCIPAL_ID=$(az vm show -g AzureVM -n $VM_NAME --query "identity.principalId" -otsv)
            az role assignment delete --assignee $PRINCIPAL_ID --role "Key Vault Secrets User" --resource-group "AzureVM" || true
            az resource delete --ids $(az resource list --tag deploymentgroup=$VM_NAME -otable --query "[].id" -otsv)

      # - uses: act10ns/slack@v1
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: '#builds'
      #   if: always()


# to generate AZURE_CREDENTIALS github secret:

#az ad sp create-for-rbac --name "GithubActionsServicePrincipal" --role contributor --scopes /subscriptions/5b05ad77-2db4-4691-a3af-6fd0ba4294a3/resourceGroups/AzureVm --sdk-auth