name: Trigger Build on Push

on:
  push:
    branches:
      - develop
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build and Publish Workflow

    steps:

    - name: Extract Branch
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Build Docker Image
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        workflow: Build and Publish Docker Image
        token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        inputs: '{ "git_commit": "${{ steps.extract_branch.outputs.branch }}" }'

    - name: Build VM
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        repo: jamesfera/actionstest
        workflow: Create and Bootstrap Virtual Machine
        token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        inputs: '{ "name": "${{ steps.extract_branch.outputs.branch }}", "swarm": "true" }'

    - name: Deploy
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        repo: jamesfera/actionstest
        workflow: Docker Image Deployment
        token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        inputs: '{ "host": "aexautodeploy${{steps.extract_branch.outputs.branch}}.eastus.cloudapp.azure.com", "deployment_subdomain": "${{steps.extract_branch.outputs.branch}}" }'