name: Trigger VM Build

on:
  pull_request:  

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build VM   

    steps:

    - name: Build Docker Image
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        workflow: Build and Publish Docker Image
        token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
        inputs: '{ "git_commit": "${{ github.event.pull_request.head.ref }}", "image_tag": "pr${{ github.event.pull_request.number }}" }'

    # - name: Build VM
    #   uses: aurelien-baudet/workflow-dispatch@v2
    #   with:
    #     workflow: Create and Bootstrap Virtual Machine
    #     token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
    #     inputs: '{ "name": "pushtest", "swarm": "false" }'

    # - name: Deploy
    #   uses: aurelien-baudet/workflow-dispatch@v2
    #   with:
    #     workflow: Create and Bootstrap Virtual Machine
    #     token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}
    #     inputs: '{ "name": "pushtest", "swarm": "false" }'